
const fakeData = [
  {
    artist: 'Bryana Harvey',
    songName: 'SUMMOAK',
    albumPic: 'http://lorempixel.com/640/400/fashion',
    artistPic: 'http://lorempixel.com/640/480/people',
    location: 'Merlside, Haiti',
    comments: 966,
    plays: 8378,
    likes: 94,
    reposts: 347,
    pro: true,
    primarySong: 1,
  },
  {
    artist: 'Verdie Rempel',
    songName: 'twas Lil Kim',
    albumPic: 'http://lorempixel.com/400/480/sports',
    artistPic: 'http://lorempixel.com/640/480/people',
    location: 'Jaceton, Paraguay',
    comments: 95,
    plays: 5876,
    likes: 3495,
    reposts: 0,
    pro: false,
    primarySong: 1,
  },
  {
    artist: 'Marcus Auer',
    songName: 'Hardboiled',
    albumPic: 'http://lorempixel.com/640/480/abstract',
    artistPic: 'http://lorempixel.com/640/480/people',
    location: 'Tianaburgh, Cayman Islands',
    comments: 297,
    plays: 8759,
    likes: 27,
    reposts: 400,
    pro: false,
    primarySong: 1,
  },
];

export default fakeData;


// const fakeData = [
//   [
//     'Bryana Harvey',
//     'http://lorempixel.com/640/480',
//     'http://lorempixel.com/640/480/people', 'Merlside, Haiti',
//     966,
//     8378,
//     94,
//     347,
//     true,
//     1],
//   [
//     'Verdie Rempel',
//     'http://lorempixel.com/640/480',
//     'http://lorempixel.com/640/480/people',
//     'Jaceton, Paraguay',
//     4606,
//     5876,
//     96,
//     0,
//     false,
//     1,
//   ],
//   [
//     'Marcus Auer',
//     'http://lorempixel.com/640/480',
//     'http://lorempixel.com/640/480/people',
//     'Tianaburgh, Cayman Islands',
//     297,
//     8759,
//     27,
//     1009,
//     false,
//     1,
//   ],
// ];
